// Generated by ts-to-zod
import { z } from "zod";

export const baseModelSchema = z.object({
    id: z.string()
});

export const logModelSchema = baseModelSchema.extend({
    level: z.string(),
    message: z.string(),
    created: z.string(),
    updated: z.string(),
    data: z.record(z.string(), z.any())
});

export const recordModelSchema = baseModelSchema.extend({
    collectionId: z.string(),
    collectionName: z.string(),
    expand: z.record(z.string(), z.any()).optional()
});

export const collectionFieldSchema = z.record(z.string(), z.any()).and(z.object({
    id: z.string(),
    name: z.string(),
    type: z.string(),
    system: z.boolean(),
    hidden: z.boolean(),
    presentable: z.boolean()
}));

export const tokenConfigSchema = z.object({
    duration: z.number(),
    secret: z.string().optional()
});

export const emailTemplateSchema = z.object({
    subject: z.string(),
    body: z.string()
});

export const otpConfigSchema = z.object({
    enabled: z.boolean(),
    duration: z.number(),
    length: z.number(),
    emailTemplate: emailTemplateSchema
});

export const mfaConfigSchema = z.object({
    enabled: z.boolean(),
    duration: z.number(),
    rule: z.string()
});

export const passwordAuthConfigSchema = z.object({
    enabled: z.boolean(),
    identityFields: z.array(z.string())
});

export const oAuth2ProviderSchema = z.object({
    pkce: z.boolean().optional(),
    clientId: z.string(),
    name: z.string(),
    clientSecret: z.string(),
    authURL: z.string(),
    tokenURL: z.string(),
    userInfoURL: z.string(),
    displayName: z.string(),
    extra: z.record(z.string(), z.any()).optional()
});

export const oAuth2ConfigSchema = z.object({
    enabled: z.boolean(),
    mappedFields: z.record(z.string(), z.string()),
    providers: z.array(oAuth2ProviderSchema)
});

export const collectionSchema = baseModelSchema.extend({
    name: z.string(),
    fields: z.array(collectionFieldSchema),
    indexes: z.array(z.string()),
    system: z.boolean(),
    listRule: z.string().optional(),
    viewRule: z.string().optional(),
    createRule: z.string().optional(),
    updateRule: z.string().optional(),
    deleteRule: z.string().optional()
});

export const baseCollectionModelSchema = collectionSchema.extend({
    type: z.literal("base")
});

export const viewCollectionModelSchema = collectionSchema.extend({
    type: z.literal("view"),
    viewQuery: z.string()
});

export const authAlertConfigSchema = z.object({
    enabled: z.boolean(),
    emailTemplate: emailTemplateSchema
});

export const authCollectionModelSchema = collectionSchema.extend({
    type: z.literal("auth"),
    authRule: z.string().optional(),
    manageRule: z.string().optional(),
    authAlert: authAlertConfigSchema,
    oauth2: oAuth2ConfigSchema,
    passwordAuth: passwordAuthConfigSchema,
    mfa: mfaConfigSchema,
    otp: otpConfigSchema,
    authToken: tokenConfigSchema,
    passwordResetToken: tokenConfigSchema,
    emailChangeToken: tokenConfigSchema,
    verificationToken: tokenConfigSchema,
    fileToken: tokenConfigSchema,
    verificationTemplate: emailTemplateSchema,
    resetPasswordTemplate: emailTemplateSchema,
    confirmEmailChangeTemplate: emailTemplateSchema
});

export const authRecordSchema = recordModelSchema.nullable();

export const appleClientSecretSchema = z.object({
    secret: z.string()
});

export const authProviderInfoSchema = z.object({
    name: z.string(),
    displayName: z.string(),
    state: z.string(),
    authURL: z.string(),
    codeVerifier: z.string(),
    codeChallenge: z.string(),
    codeChallengeMethod: z.string()
});

export const authMethodsListSchema = z.object({
    mfa: z.object({
        enabled: z.boolean(),
        duration: z.number()
    }),
    otp: z.object({
        enabled: z.boolean(),
        duration: z.number()
    }),
    password: z.object({
        enabled: z.boolean(),
        identityFields: z.array(z.string())
    }),
    oauth2: z.object({
        enabled: z.boolean(),
        providers: z.array(authProviderInfoSchema)
    })
});

export const otpResponseSchema = z.object({
    otpId: z.string()
});

export const hourlyStatsSchema = z.object({
    total: z.number(),
    date: z.string()
});

export const healthCheckResponseSchema = z.object({
    code: z.number(),
    message: z.string(),
    data: z.record(z.string(), z.any())
});

export const backupFileInfoSchema = z.object({
    key: z.string(),
    size: z.number(),
    modified: z.string()
});

export const cronJobSchema = z.object({
    id: z.string(),
    expression: z.string()
});

export const batchRequestSchema = z.object({
    method: z.string(),
    url: z.string(),
    json: z.record(z.string(), z.any()).optional(),
    files: z.record(z.string(), z.array(z.any())).optional(),
    headers: z.record(z.string(), z.string()).optional()
});

export const batchRequestResultSchema = z.object({
    status: z.number(),
    body: z.any().optional()
});

export const collectionModelSchema = z.union([baseCollectionModelSchema, viewCollectionModelSchema, authCollectionModelSchema]);
